### ISSUE TITLE
Do not work on Ubuntu 14.04

### ISSUE THREAD

**Issue by zloidemon** [shveenkov/aiotarantool#1]
```
# cat tt.py
#!/usr/bin/env python3

import asyncio
import aiotarantool

cnt = 0

@asyncio.coroutine
def insert_job(tnt):
    global cnt

    for it in range(10):
        cnt += 1
        r = yield from tnt.insert("tester", (cnt, cnt))

loop = asyncio.get_event_loop()

tnt = aiotarantool.connect("127.0.0.1", 3301)
tasks = [asyncio.async(insert_job(tnt))
         for _ in range(10)]

loop.run_until_complete(asyncio.wait(tasks))
loop.run_until_complete(tnt.close())
loop.close()
```

```
# pip list
aiotarantool (1.0.3)
msgpack-python (0.4.6)
pip (1.5.4)
PyYAML (3.11)
setuptools (2.2)
tarantool (0.5.1)
(.venv)root@aster-runexis:~/python# ./tt.py
Traceback (most recent call last):
  File "./tt.py", line 23, in <module>
    loop.run_until_complete(tnt.close())
  File "/usr/lib/python3.4/asyncio/base_events.py", line 208, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 243, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 302, in _step
    result = next(coro)
  File "/root/python/.venv/lib/python3.4/site-packages/aiotarantool.py", line 285, in close
    yield from self._do_close(None)
  File "/root/python/.venv/lib/python3.4/site-packages/aiotarantool.py", line 294, in _do_close
    self._reader_task.cancel()
AttributeError: 'NoneType' object has no attribute 'cancel'
--- Logging error ---
Traceback (most recent call last):
--- Logging error ---
Traceback (most recent call last):
Exception ignored in: <bound method Task.__del__ of Task(<insert_job>)<exception=AttributeError("'_UnixSelectorEventLoop' object has no attribute 'create_task'",)>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/futures.py", line 184, in __del__
  File "/usr/lib/python3.4/asyncio/base_events.py", line 725, in call_exception_handler
  File "/usr/lib/python3.4/logging/__init__.py", line 1289, in error
  File "/usr/lib/python3.4/logging/__init__.py", line 1395, in _log
  File "/usr/lib/python3.4/logging/__init__.py", line 1405, in handle
  File "/usr/lib/python3.4/logging/__init__.py", line 1475, in callHandlers
  File "/usr/lib/python3.4/logging/__init__.py", line 839, in handle
  File "/usr/lib/python3.4/logging/__init__.py", line 970, in emit
  File "/usr/lib/python3.4/logging/__init__.py", line 892, in handleError
  File "/usr/lib/python3.4/traceback.py", line 169, in print_exception
  File "/usr/lib/python3.4/traceback.py", line 153, in _format_exception_iter
  File "/usr/lib/python3.4/traceback.py", line 18, in _format_list_iter
  File "/usr/lib/python3.4/traceback.py", line 65, in _extract_tb_or_stack_iter
  File "/root/python/.venv/lib/python3.4/linecache.py", line 15, in getline
  File "/root/python/.venv/lib/python3.4/linecache.py", line 41, in getlines
  File "/root/python/.venv/lib/python3.4/linecache.py", line 131, in updatecache
  File "/root/python/.venv/lib/python3.4/tokenize.py", line 437, in open
AttributeError: 'module' object has no attribute 'open'
--- Logging error ---
Traceback (most recent call last):
--- Logging error ---
Traceback (most recent call last):
```

**Comment by shveenkov** [comment]
need python ver ge 3.4.3
